import Head from "next/head";
import Link from 'next/link';

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>BWA Micro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Saya Halaman utama</h1>
      </main>

      <Link href="/random" legacyBehavior>
        <a>Bring me to random fetch page</a>
      </Link>
    </div>
  );
}
